export enum Icon {
  Account = 'account',
  BackArrow = 'back-arrow',
  Bolt = 'bolt',
  External = 'external',
  Eye = 'eye',
  FastForward = 'fast-forward',
  Home = 'home',
  Moon = 'moon',
  Ninja = 'ninja',
  Rewind = 'rewind',
  Save = 'save',
  Sun = 'sun',
  ThreeLines = 'three-lines',
  Tools = 'tools',
  Upload = 'upload',
  Write = 'write',
}
