export enum Icon {
  Account = 'account',
  BackArrow = 'back-arrow',
  Bolt = 'bolt',
  Changelog = 'changelog',
  External = 'external',
  Eye = 'eye',
  Home = 'home',
  Moon = 'moon',
  Ninja = 'ninja',
  Sun = 'sun',
  ThreeLines = 'three-lines',
  Upload = 'upload',
  Write = 'write',
}
